### ISSUE TITLE
Intel Power Gadeget Issue

### ISSUE THREAD

**Issue by SatyamVyas00** [KadeReolance/Predator-Helios-300-OpenCore-0.6.0#1]
Wheenever i open intel xtu whole system get hanged and i have to force shutdown

**Comment by KadeReolance** [comment]
i have the same issue as of now. I tried both Virtual SMC and Fake SMC doesn't seem to work. Still searching for solutions

**Comment by KadeReolance** [comment]
Fix in commit [29c81d9
](https://github.com/KadeReolance/Predator-Helios-300-OpenCore-0.6.0/commit/b3b156121c7f079859b6ebb8f84ebc7b00a9c1de)
